# Generated by Django 4.1.7 on 2023-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='user.png', upload_to='media/'),
        ),
    ]
