# Generated by Django 4.1.7 on 2023-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
