# Generated by Django 4.1.7 on 2023-03-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('is_template', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'Initialized'), (1, 'Sent'), (2, 'Read')], default=0)),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_logs', to='dashboard.mail')),
            ],
        ),
    ]
