# Generated by Django 4.1.7 on 2023-03-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_img'),
        ('dashboard', '0002_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_templates', to='users.profile'),
        ),
        migrations.AddField(
            model_name='templates',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
