# Generated by Django 4.1.7 on 2023-03-22 11:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_templates_created_by_templates_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
