# Generated by Django 4.1.7 on 2023-03-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_mail_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='is_template',
        ),
    ]
