# Generated by Django 4.1.7 on 2023-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initialized'), (1, 'Sent'), (2, 'Read'), (3, 'Failed')], default=0),
        ),
    ]
