# Generated by Django 4.1.7 on 2023-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
