# Generated by Django 4.1.7 on 2023-03-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_mail_mail_from'),
        ('dashboard', '0008_log_read_at_log_sent_at_mail_created_at'),
    ]

    operations = [
    ]
